sudo: false
language: node_js
node_js:
  - "8.2.1"
env:
  global:
    - YARN_VERSION=0.27.5

notifications:
  email: evenchange4@gmail.com

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

install:
  - echo "none"

jobs:
  include:
    - stage: Install Dependencies
      script: |
        yarn install
    - stage: Test
      script: yarn run danger
      env:
        - TRAVIS_JOB_NAME=danger
    - script: ./tasks/lint.sh
      env:
        - TRAVIS_JOB_NAME=lint
    - script: ./tasks/test.sh
      env:
        - TRAVIS_JOB_NAME=test
      after_success:
        - ./node_modules/.bin/codecov
    - script: ./tasks/test-page.sh
      env:
        - TRAVIS_JOB_NAME=test-page
    - script: skip
      env:
        - TRAVIS_JOB_NAME=cache
      cache:
        yarn: true
        directories:
          - $HOME/.yarn
          - node_modules
          - packages/mcs-lite-introduction/node_modules
