sudo: false
language: node_js
services:
  - docker

before_install:
  - docker pull node:8.2.1

install:
  - echo "[Skip] Use job stage to warm up cache"

cache:
  yarn: true
  directories:
    - $HOME/.yarn
    - node_modules

jobs:
  include:
    # Prepare npm and Warm up cache
    - stage: Install Dependencies and Cache
      script: yarn install --pure-lockfile
    # Use cache
    - stage: Test
      script: yarn run danger
    - script: yarn run postinstall && ./tasks/lint.sh
    - script: yarn run postinstall && ./tasks/test-page.sh
    - script: yarn run postinstall && ./tasks/test.sh
      after_success:
        - ./node_modules/.bin/codecov

notifications:
  email: evenchange4@gmail.com
