sudo: false
language: node_js
node_js:
  - "8.2.1"
env:
  global:
    - YARN_VERSION=0.27.5

notifications:
  email: evenchange4@gmail.com

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

script:
  - yarn run danger
  - ./tasks/test.sh
  - ./tasks/test-page.sh

after_success:
  - ./node_modules/.bin/codecov

cache:
  yarn: true
  directories:
    - ~/.yarn
    - node_modules
    - packages/mcs-lite-introduction/node_modules
