sudo: false
language: node_js
node_js:
  - "8.2.1"
env:
  global:
    - YARN_VERSION=0.27.5

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

install:
  - echo "none"

jobs:
  include:
    # Prepare npm and cache
    - stage: Install Dependencies and Cache
      script: yarn install --pure-lockfile
      cache:
        yarn: true
        directories:
          - $HOME/.yarn
          - node_modules

    # Use cache
    - stage: Test
      script:  yarn run danger
    - script: yarn run postinstall && ./tasks/lint.sh
    - script: yarn run postinstall && ./tasks/test-page.sh
    - script: yarn run postinstall && ./tasks/test.sh
      after_success:
        - ./node_modules/.bin/codecov

notifications:
  email: evenchange4@gmail.com
