# Global settings applied to the whole site.
[build]
  command = "yarn --version && which yarn"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview.environment]
  command = "npm i yarn@0.27.5 -g"
