// flow-typed signature: 5c4f529aa1f16a961ed3c8c555a4474a
// flow-typed version: <<STUB>>/babel-preset-mcs-lite_v^0.3.25/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-mcs-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-mcs-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-mcs-lite/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/__tests__/mcs-lite-icon.test' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/__tests__/mcs-lite-ui.test' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/__tests__/ramda.test' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/__tests__/recharts.test' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/__tests__/recompose.test' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'babel-preset-mcs-lite/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-mcs-lite/__tests__/index.test.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/__tests__/index.test',
  >;
}
declare module 'babel-preset-mcs-lite/__tests__/mcs-lite-icon.test.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/__tests__/mcs-lite-icon.test',
  >;
}
declare module 'babel-preset-mcs-lite/__tests__/mcs-lite-ui.test.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/__tests__/mcs-lite-ui.test',
  >;
}
declare module 'babel-preset-mcs-lite/__tests__/ramda.test.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/__tests__/ramda.test',
  >;
}
declare module 'babel-preset-mcs-lite/__tests__/recharts.test.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/__tests__/recharts.test',
  >;
}
declare module 'babel-preset-mcs-lite/__tests__/recompose.test.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/__tests__/recompose.test',
  >;
}
declare module 'babel-preset-mcs-lite/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/coverage/lcov-report/block-navigation',
  >;
}
declare module 'babel-preset-mcs-lite/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/coverage/lcov-report/prettify',
  >;
}
declare module 'babel-preset-mcs-lite/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<
    'babel-preset-mcs-lite/coverage/lcov-report/sorter',
  >;
}
declare module 'babel-preset-mcs-lite/index' {
  declare module.exports: $Exports<'babel-preset-mcs-lite'>;
}
declare module 'babel-preset-mcs-lite/index.js' {
  declare module.exports: $Exports<'babel-preset-mcs-lite'>;
}
