// flow-typed signature: c2e0fb5b69861d60ae46776b3d1cf73e
// flow-typed version: <<STUB>>/bowser_v^1.9.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bowser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bowser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bowser/bowser' {
  declare module.exports: any;
}

declare module 'bowser/bowser.min' {
  declare module.exports: any;
}

declare module 'bowser/src/bowser' {
  declare module.exports: any;
}

declare module 'bowser/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bowser/bowser.js' {
  declare module.exports: $Exports<'bowser/bowser'>;
}
declare module 'bowser/bowser.min.js' {
  declare module.exports: $Exports<'bowser/bowser.min'>;
}
declare module 'bowser/src/bowser.js' {
  declare module.exports: $Exports<'bowser/src/bowser'>;
}
declare module 'bowser/test/test.js' {
  declare module.exports: $Exports<'bowser/test/test'>;
}
