// flow-typed signature: ce0710e95454fdd4585dbd8cb75949e1
// flow-typed version: <<STUB>>/bowser_v1.9.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bowser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bowser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bowser/bowser' {
  declare module.exports: any;
}

declare module 'bowser/bowser.min' {
  declare module.exports: any;
}

declare module 'bowser/src/bowser' {
  declare module.exports: any;
}

declare module 'bowser/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bowser/bowser.js' {
  declare module.exports: $Exports<'bowser/bowser'>;
}
declare module 'bowser/bowser.min.js' {
  declare module.exports: $Exports<'bowser/bowser.min'>;
}
declare module 'bowser/src/bowser.js' {
  declare module.exports: $Exports<'bowser/src/bowser'>;
}
declare module 'bowser/test/test.js' {
  declare module.exports: $Exports<'bowser/test/test'>;
}
