// flow-typed signature: c51b8846557a7420d6e0da8090460c01
// flow-typed version: <<STUB>>/browser-locale_v1.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-locale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-locale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'browser-locale/index' {
  declare module.exports: $Exports<'browser-locale'>;
}
declare module 'browser-locale/index.js' {
  declare module.exports: $Exports<'browser-locale'>;
}
