// flow-typed signature: 8d935e083dcb66a3a617d9aacd06a1ed
// flow-typed version: <<STUB>>/flubber_v0.4.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flubber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flubber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flubber/build/flubber.min' {
  declare module.exports: any;
}

declare module 'flubber/src/add' {
  declare module.exports: any;
}

declare module 'flubber/src/errors' {
  declare module.exports: any;
}

declare module 'flubber/src/interpolate' {
  declare module.exports: any;
}

declare module 'flubber/src/math' {
  declare module.exports: any;
}

declare module 'flubber/src/multiple' {
  declare module.exports: any;
}

declare module 'flubber/src/normalize' {
  declare module.exports: any;
}

declare module 'flubber/src/order' {
  declare module.exports: any;
}

declare module 'flubber/src/rotate' {
  declare module.exports: any;
}

declare module 'flubber/src/shape' {
  declare module.exports: any;
}

declare module 'flubber/src/svg' {
  declare module.exports: any;
}

declare module 'flubber/src/topology' {
  declare module.exports: any;
}

declare module 'flubber/src/triangulate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flubber/build/flubber.min.js' {
  declare module.exports: $Exports<'flubber/build/flubber.min'>;
}
declare module 'flubber/index' {
  declare module.exports: $Exports<'flubber'>;
}
declare module 'flubber/index.js' {
  declare module.exports: $Exports<'flubber'>;
}
declare module 'flubber/src/add.js' {
  declare module.exports: $Exports<'flubber/src/add'>;
}
declare module 'flubber/src/errors.js' {
  declare module.exports: $Exports<'flubber/src/errors'>;
}
declare module 'flubber/src/interpolate.js' {
  declare module.exports: $Exports<'flubber/src/interpolate'>;
}
declare module 'flubber/src/math.js' {
  declare module.exports: $Exports<'flubber/src/math'>;
}
declare module 'flubber/src/multiple.js' {
  declare module.exports: $Exports<'flubber/src/multiple'>;
}
declare module 'flubber/src/normalize.js' {
  declare module.exports: $Exports<'flubber/src/normalize'>;
}
declare module 'flubber/src/order.js' {
  declare module.exports: $Exports<'flubber/src/order'>;
}
declare module 'flubber/src/rotate.js' {
  declare module.exports: $Exports<'flubber/src/rotate'>;
}
declare module 'flubber/src/shape.js' {
  declare module.exports: $Exports<'flubber/src/shape'>;
}
declare module 'flubber/src/svg.js' {
  declare module.exports: $Exports<'flubber/src/svg'>;
}
declare module 'flubber/src/topology.js' {
  declare module.exports: $Exports<'flubber/src/topology'>;
}
declare module 'flubber/src/triangulate.js' {
  declare module.exports: $Exports<'flubber/src/triangulate'>;
}
