// flow-typed signature: 8555d3f547cde980b464f27bf8e5b196
// flow-typed version: <<STUB>>/hedron_v0.7.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hedron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hedron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hedron/dist/hedron.es' {
  declare module.exports: any;
}

declare module 'hedron/dist/hedron' {
  declare module.exports: any;
}

declare module 'hedron/dist/hedron.min' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-plugin-external-helpers_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-preset-latest_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/babel-preset-stage-2_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-inject_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-replace_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/flow-typed/npm/rollup-plugin-uglify_vx.x.x' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Box' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/BreakpointProvider' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Column' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Container' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Hidden' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/LayoutProvider' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Page' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Row' {
  declare module.exports: any;
}

declare module 'hedron/lib/components/Section' {
  declare module.exports: any;
}

declare module 'hedron/lib/constants' {
  declare module.exports: any;
}

declare module 'hedron/lib/index' {
  declare module.exports: any;
}

declare module 'hedron/lib/index.test' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/breakpoint' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/divvy' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/flex' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/index' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/media' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/passOn' {
  declare module.exports: any;
}

declare module 'hedron/lib/utils/styles' {
  declare module.exports: any;
}

declare module 'hedron/src/components/BreakpointProvider' {
  declare module.exports: any;
}

declare module 'hedron/src/components/Column' {
  declare module.exports: any;
}

declare module 'hedron/src/components/Hidden' {
  declare module.exports: any;
}

declare module 'hedron/src/components/Page' {
  declare module.exports: any;
}

declare module 'hedron/src/components/Row' {
  declare module.exports: any;
}

declare module 'hedron/src/index' {
  declare module.exports: any;
}

declare module 'hedron/src/index.test' {
  declare module.exports: any;
}

declare module 'hedron/src/utils/breakpoint' {
  declare module.exports: any;
}

declare module 'hedron/src/utils/divvy' {
  declare module.exports: any;
}

declare module 'hedron/src/utils/index' {
  declare module.exports: any;
}

declare module 'hedron/src/utils/media' {
  declare module.exports: any;
}

declare module 'hedron/src/utils/passOn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hedron/dist/hedron.es.js' {
  declare module.exports: $Exports<'hedron/dist/hedron.es'>;
}
declare module 'hedron/dist/hedron.js' {
  declare module.exports: $Exports<'hedron/dist/hedron'>;
}
declare module 'hedron/dist/hedron.min.js' {
  declare module.exports: $Exports<'hedron/dist/hedron.min'>;
}
declare module 'hedron/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-plugin-add-module-exports_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-plugin-external-helpers_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-plugin-external-helpers_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-plugin-flow-react-proptypes_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-preset-es2015_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-preset-es2015-rollup_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-preset-latest_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-preset-latest_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-preset-react_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/babel-preset-stage-2_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/babel-preset-stage-2_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/eslint-config-airbnb_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/eslint-plugin-import_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/eslint-plugin-react_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'hedron/flow-typed/npm/jest_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/jest_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/react-test-renderer_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'hedron/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-babel_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-commonjs_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-inject_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-inject_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-json_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-json_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-node-resolve_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-replace_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-replace_vx.x.x',
  >;
}
declare module 'hedron/flow-typed/npm/rollup-plugin-uglify_vx.x.x.js' {
  declare module.exports: $Exports<
    'hedron/flow-typed/npm/rollup-plugin-uglify_vx.x.x',
  >;
}
declare module 'hedron/lib/components/Box.js' {
  declare module.exports: $Exports<'hedron/lib/components/Box'>;
}
declare module 'hedron/lib/components/BreakpointProvider.js' {
  declare module.exports: $Exports<'hedron/lib/components/BreakpointProvider'>;
}
declare module 'hedron/lib/components/Column.js' {
  declare module.exports: $Exports<'hedron/lib/components/Column'>;
}
declare module 'hedron/lib/components/Container.js' {
  declare module.exports: $Exports<'hedron/lib/components/Container'>;
}
declare module 'hedron/lib/components/Hidden.js' {
  declare module.exports: $Exports<'hedron/lib/components/Hidden'>;
}
declare module 'hedron/lib/components/LayoutProvider.js' {
  declare module.exports: $Exports<'hedron/lib/components/LayoutProvider'>;
}
declare module 'hedron/lib/components/Page.js' {
  declare module.exports: $Exports<'hedron/lib/components/Page'>;
}
declare module 'hedron/lib/components/Row.js' {
  declare module.exports: $Exports<'hedron/lib/components/Row'>;
}
declare module 'hedron/lib/components/Section.js' {
  declare module.exports: $Exports<'hedron/lib/components/Section'>;
}
declare module 'hedron/lib/constants.js' {
  declare module.exports: $Exports<'hedron/lib/constants'>;
}
declare module 'hedron/lib/index.js' {
  declare module.exports: $Exports<'hedron/lib/index'>;
}
declare module 'hedron/lib/index.test.js' {
  declare module.exports: $Exports<'hedron/lib/index.test'>;
}
declare module 'hedron/lib/utils/breakpoint.js' {
  declare module.exports: $Exports<'hedron/lib/utils/breakpoint'>;
}
declare module 'hedron/lib/utils/divvy.js' {
  declare module.exports: $Exports<'hedron/lib/utils/divvy'>;
}
declare module 'hedron/lib/utils/flex.js' {
  declare module.exports: $Exports<'hedron/lib/utils/flex'>;
}
declare module 'hedron/lib/utils/index.js' {
  declare module.exports: $Exports<'hedron/lib/utils/index'>;
}
declare module 'hedron/lib/utils/media.js' {
  declare module.exports: $Exports<'hedron/lib/utils/media'>;
}
declare module 'hedron/lib/utils/passOn.js' {
  declare module.exports: $Exports<'hedron/lib/utils/passOn'>;
}
declare module 'hedron/lib/utils/styles.js' {
  declare module.exports: $Exports<'hedron/lib/utils/styles'>;
}
declare module 'hedron/src/components/BreakpointProvider.js' {
  declare module.exports: $Exports<'hedron/src/components/BreakpointProvider'>;
}
declare module 'hedron/src/components/Column.js' {
  declare module.exports: $Exports<'hedron/src/components/Column'>;
}
declare module 'hedron/src/components/Hidden.js' {
  declare module.exports: $Exports<'hedron/src/components/Hidden'>;
}
declare module 'hedron/src/components/Page.js' {
  declare module.exports: $Exports<'hedron/src/components/Page'>;
}
declare module 'hedron/src/components/Row.js' {
  declare module.exports: $Exports<'hedron/src/components/Row'>;
}
declare module 'hedron/src/index.js' {
  declare module.exports: $Exports<'hedron/src/index'>;
}
declare module 'hedron/src/index.test.js' {
  declare module.exports: $Exports<'hedron/src/index.test'>;
}
declare module 'hedron/src/utils/breakpoint.js' {
  declare module.exports: $Exports<'hedron/src/utils/breakpoint'>;
}
declare module 'hedron/src/utils/divvy.js' {
  declare module.exports: $Exports<'hedron/src/utils/divvy'>;
}
declare module 'hedron/src/utils/index.js' {
  declare module.exports: $Exports<'hedron/src/utils/index'>;
}
declare module 'hedron/src/utils/media.js' {
  declare module.exports: $Exports<'hedron/src/utils/media'>;
}
declare module 'hedron/src/utils/passOn.js' {
  declare module.exports: $Exports<'hedron/src/utils/passOn'>;
}
