// flow-typed signature: 02221023e9f51dfbf98b4264cc78f033
// flow-typed version: <<STUB>>/lerna-changelog_v^0.6.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerna-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerna-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lerna-changelog/bin/cli' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/api-data-cache' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/changelog' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/configuration-error' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/configuration' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/find-pull-request-id' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/git' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/github-api' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/index' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/interfaces' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/markdown-renderer' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/progress-bar' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/remote-repo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lerna-changelog/bin/cli.js' {
  declare module.exports: $Exports<'lerna-changelog/bin/cli'>;
}
declare module 'lerna-changelog/index' {
  declare module.exports: $Exports<'lerna-changelog'>;
}
declare module 'lerna-changelog/index.js' {
  declare module.exports: $Exports<'lerna-changelog'>;
}
declare module 'lerna-changelog/lib/api-data-cache.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/api-data-cache'>;
}
declare module 'lerna-changelog/lib/changelog.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/changelog'>;
}
declare module 'lerna-changelog/lib/configuration-error.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/configuration-error'>;
}
declare module 'lerna-changelog/lib/configuration.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/configuration'>;
}
declare module 'lerna-changelog/lib/find-pull-request-id.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/find-pull-request-id'>;
}
declare module 'lerna-changelog/lib/git.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/git'>;
}
declare module 'lerna-changelog/lib/github-api.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/github-api'>;
}
declare module 'lerna-changelog/lib/index.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/index'>;
}
declare module 'lerna-changelog/lib/interfaces.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/interfaces'>;
}
declare module 'lerna-changelog/lib/markdown-renderer.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/markdown-renderer'>;
}
declare module 'lerna-changelog/lib/progress-bar.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/progress-bar'>;
}
declare module 'lerna-changelog/lib/remote-repo.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/remote-repo'>;
}
