// flow-typed signature: 57fc5f8411b64ce4f00cb5087656c65b
// flow-typed version: <<STUB>>/lerna-changelog_v^0.5.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerna-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerna-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lerna-changelog/bin/cli' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/ApiDataCache' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/Changelog' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/Configuration' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/ConfigurationError' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/execSync' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/GithubAPI' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/index' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/progressBar' {
  declare module.exports: any;
}

declare module 'lerna-changelog/lib/RemoteRepo' {
  declare module.exports: any;
}

declare module 'lerna-changelog/test/Changelog.spec' {
  declare module.exports: any;
}

declare module 'lerna-changelog/test/Configuration.spec' {
  declare module.exports: any;
}

declare module 'lerna-changelog/test/functional/markdown-full.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lerna-changelog/bin/cli.js' {
  declare module.exports: $Exports<'lerna-changelog/bin/cli'>;
}
declare module 'lerna-changelog/index' {
  declare module.exports: $Exports<'lerna-changelog'>;
}
declare module 'lerna-changelog/index.js' {
  declare module.exports: $Exports<'lerna-changelog'>;
}
declare module 'lerna-changelog/lib/ApiDataCache.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/ApiDataCache'>;
}
declare module 'lerna-changelog/lib/Changelog.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/Changelog'>;
}
declare module 'lerna-changelog/lib/Configuration.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/Configuration'>;
}
declare module 'lerna-changelog/lib/ConfigurationError.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/ConfigurationError'>;
}
declare module 'lerna-changelog/lib/execSync.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/execSync'>;
}
declare module 'lerna-changelog/lib/GithubAPI.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/GithubAPI'>;
}
declare module 'lerna-changelog/lib/index.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/index'>;
}
declare module 'lerna-changelog/lib/progressBar.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/progressBar'>;
}
declare module 'lerna-changelog/lib/RemoteRepo.js' {
  declare module.exports: $Exports<'lerna-changelog/lib/RemoteRepo'>;
}
declare module 'lerna-changelog/test/Changelog.spec.js' {
  declare module.exports: $Exports<'lerna-changelog/test/Changelog.spec'>;
}
declare module 'lerna-changelog/test/Configuration.spec.js' {
  declare module.exports: $Exports<'lerna-changelog/test/Configuration.spec'>;
}
declare module 'lerna-changelog/test/functional/markdown-full.spec.js' {
  declare module.exports: $Exports<'lerna-changelog/test/functional/markdown-full.spec'>;
}
