// flow-typed signature: ceabe07ae95bf393fd69d7e64bb0f184
// flow-typed version: <<STUB>>/license-checker_v16.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'license-checker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'license-checker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'license-checker/lib/args' {
  declare module.exports: any;
}

declare module 'license-checker/lib/index' {
  declare module.exports: any;
}

declare module 'license-checker/lib/license' {
  declare module.exports: any;
}

declare module 'license-checker/lib/stack' {
  declare module.exports: any;
}

declare module 'license-checker/scripts/contrib' {
  declare module.exports: any;
}

declare module 'license-checker/tests/bin-test' {
  declare module.exports: any;
}

declare module 'license-checker/tests/failOn-test' {
  declare module.exports: any;
}

declare module 'license-checker/tests/license' {
  declare module.exports: any;
}

declare module 'license-checker/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'license-checker/lib/args.js' {
  declare module.exports: $Exports<'license-checker/lib/args'>;
}
declare module 'license-checker/lib/index.js' {
  declare module.exports: $Exports<'license-checker/lib/index'>;
}
declare module 'license-checker/lib/license.js' {
  declare module.exports: $Exports<'license-checker/lib/license'>;
}
declare module 'license-checker/lib/stack.js' {
  declare module.exports: $Exports<'license-checker/lib/stack'>;
}
declare module 'license-checker/scripts/contrib.js' {
  declare module.exports: $Exports<'license-checker/scripts/contrib'>;
}
declare module 'license-checker/tests/bin-test.js' {
  declare module.exports: $Exports<'license-checker/tests/bin-test'>;
}
declare module 'license-checker/tests/failOn-test.js' {
  declare module.exports: $Exports<'license-checker/tests/failOn-test'>;
}
declare module 'license-checker/tests/license.js' {
  declare module.exports: $Exports<'license-checker/tests/license'>;
}
declare module 'license-checker/tests/test.js' {
  declare module.exports: $Exports<'license-checker/tests/test'>;
}
