// flow-typed signature: 18818313bac3c4b596a82469499acaaf
// flow-typed version: <<STUB>>/mcs-lite-icon_v^0.3.10/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mcs-lite-icon/lib/IconAccount' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconAdd' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconArrowLeft' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconCalendar' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconChevronRight' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconClose' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconDelete' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconDevelopment' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconDevice' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconDone' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconEdit' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconFold' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconGoDown' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconLoading' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconLogout' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconMenu' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconMoreVert' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconOverview' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconPause' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconPlay' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconPrototype' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconPublic' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconRefresh' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconResources' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconSearch' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconSetting' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconStop' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/IconSync' {
  declare module.exports: any;
}

declare module 'mcs-lite-icon/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mcs-lite-icon/lib/IconAccount.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconAccount'>;
}
declare module 'mcs-lite-icon/lib/IconAdd.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconAdd'>;
}
declare module 'mcs-lite-icon/lib/IconArrowLeft.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconArrowLeft'>;
}
declare module 'mcs-lite-icon/lib/IconCalendar.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconCalendar'>;
}
declare module 'mcs-lite-icon/lib/IconChevronRight.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconChevronRight'>;
}
declare module 'mcs-lite-icon/lib/IconClose.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconClose'>;
}
declare module 'mcs-lite-icon/lib/IconDelete.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconDelete'>;
}
declare module 'mcs-lite-icon/lib/IconDevelopment.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconDevelopment'>;
}
declare module 'mcs-lite-icon/lib/IconDevice.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconDevice'>;
}
declare module 'mcs-lite-icon/lib/IconDone.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconDone'>;
}
declare module 'mcs-lite-icon/lib/IconEdit.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconEdit'>;
}
declare module 'mcs-lite-icon/lib/IconFold.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconFold'>;
}
declare module 'mcs-lite-icon/lib/IconGoDown.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconGoDown'>;
}
declare module 'mcs-lite-icon/lib/IconLoading.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconLoading'>;
}
declare module 'mcs-lite-icon/lib/IconLogout.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconLogout'>;
}
declare module 'mcs-lite-icon/lib/IconMenu.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconMenu'>;
}
declare module 'mcs-lite-icon/lib/IconMoreVert.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconMoreVert'>;
}
declare module 'mcs-lite-icon/lib/IconOverview.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconOverview'>;
}
declare module 'mcs-lite-icon/lib/IconPause.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconPause'>;
}
declare module 'mcs-lite-icon/lib/IconPlay.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconPlay'>;
}
declare module 'mcs-lite-icon/lib/IconPrototype.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconPrototype'>;
}
declare module 'mcs-lite-icon/lib/IconPublic.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconPublic'>;
}
declare module 'mcs-lite-icon/lib/IconRefresh.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconRefresh'>;
}
declare module 'mcs-lite-icon/lib/IconResources.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconResources'>;
}
declare module 'mcs-lite-icon/lib/IconSearch.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconSearch'>;
}
declare module 'mcs-lite-icon/lib/IconSetting.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconSetting'>;
}
declare module 'mcs-lite-icon/lib/IconStop.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconStop'>;
}
declare module 'mcs-lite-icon/lib/IconSync.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/IconSync'>;
}
declare module 'mcs-lite-icon/lib/index.js' {
  declare module.exports: $Exports<'mcs-lite-icon/lib/index'>;
}
