// flow-typed signature: 445e4ea4fc63e47f63770bf2d559ef23
// flow-typed version: <<STUB>>/mcs-lite-scripts_v^0.3.10/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mcs-lite-scripts/bin/exports-all' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/bin/extract-messages' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/bin/svg-to-component' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/lib/exports-all' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/lib/extract-messages' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/lib/svg-to-component' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/lib/utils' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/src/exports-all' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/src/extract-messages' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/src/svg-to-component' {
  declare module.exports: any;
}

declare module 'mcs-lite-scripts/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mcs-lite-scripts/bin/exports-all.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/bin/exports-all'>;
}
declare module 'mcs-lite-scripts/bin/extract-messages.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/bin/extract-messages'>;
}
declare module 'mcs-lite-scripts/bin/svg-to-component.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/bin/svg-to-component'>;
}
declare module 'mcs-lite-scripts/lib/exports-all.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/lib/exports-all'>;
}
declare module 'mcs-lite-scripts/lib/extract-messages.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/lib/extract-messages'>;
}
declare module 'mcs-lite-scripts/lib/svg-to-component.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/lib/svg-to-component'>;
}
declare module 'mcs-lite-scripts/lib/utils.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/lib/utils'>;
}
declare module 'mcs-lite-scripts/src/exports-all.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/src/exports-all'>;
}
declare module 'mcs-lite-scripts/src/extract-messages.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/src/extract-messages'>;
}
declare module 'mcs-lite-scripts/src/svg-to-component.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/src/svg-to-component'>;
}
declare module 'mcs-lite-scripts/src/utils.js' {
  declare module.exports: $Exports<'mcs-lite-scripts/src/utils'>;
}
