// flow-typed signature: 003452cd3a3a4eb3cb409a76783b5ba2
// flow-typed version: <<STUB>>/mcs-lite-theme_v^0.3.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mcs-lite-theme/lib/darken' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/lib/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/lib/kindList' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/lib/opacity' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/lib/theme' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/src/darken' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/src/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/src/kindList' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/src/opacity' {
  declare module.exports: any;
}

declare module 'mcs-lite-theme/src/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mcs-lite-theme/lib/darken.js' {
  declare module.exports: $Exports<'mcs-lite-theme/lib/darken'>;
}
declare module 'mcs-lite-theme/lib/index.js' {
  declare module.exports: $Exports<'mcs-lite-theme/lib/index'>;
}
declare module 'mcs-lite-theme/lib/kindList.js' {
  declare module.exports: $Exports<'mcs-lite-theme/lib/kindList'>;
}
declare module 'mcs-lite-theme/lib/opacity.js' {
  declare module.exports: $Exports<'mcs-lite-theme/lib/opacity'>;
}
declare module 'mcs-lite-theme/lib/theme.js' {
  declare module.exports: $Exports<'mcs-lite-theme/lib/theme'>;
}
declare module 'mcs-lite-theme/src/darken.js' {
  declare module.exports: $Exports<'mcs-lite-theme/src/darken'>;
}
declare module 'mcs-lite-theme/src/index.js' {
  declare module.exports: $Exports<'mcs-lite-theme/src/index'>;
}
declare module 'mcs-lite-theme/src/kindList.js' {
  declare module.exports: $Exports<'mcs-lite-theme/src/kindList'>;
}
declare module 'mcs-lite-theme/src/opacity.js' {
  declare module.exports: $Exports<'mcs-lite-theme/src/opacity'>;
}
declare module 'mcs-lite-theme/src/theme.js' {
  declare module.exports: $Exports<'mcs-lite-theme/src/theme'>;
}
