// flow-typed signature: 46befb95ea75c2e98bf66d1e5db11238
// flow-typed version: <<STUB>>/mcs-lite-translation_v^0.1.8/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-translation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-translation' {
  declare module.exports: any;
}
