// flow-typed signature: e096f2f6a15899b5b03cb7415f1e53c8
// flow-typed version: <<STUB>>/mcs-lite-connect_v^0.3.22/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mcs-lite-connect/lib/connectSocket' {
  declare module.exports: any;
}

declare module 'mcs-lite-connect/lib/index' {
  declare module.exports: any;
}

declare module 'mcs-lite-connect/src/connectSocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mcs-lite-connect/lib/connectSocket.js' {
  declare module.exports: $Exports<'mcs-lite-connect/lib/connectSocket'>;
}
declare module 'mcs-lite-connect/lib/index.js' {
  declare module.exports: $Exports<'mcs-lite-connect/lib/index'>;
}
declare module 'mcs-lite-connect/src/connectSocket.js' {
  declare module.exports: $Exports<'mcs-lite-connect/src/connectSocket'>;
}
