// flow-typed signature: 2ee7d2ff26b4f1dca11d68c8a6df99a4
// flow-typed version: <<STUB>>/mcs-lite-translation_v^0.1.19/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mcs-lite-translation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mcs-lite-translation' {
  declare module.exports: any;
}
