// flow-typed signature: 3b5624e421f7e2c7516289f78c57cea5
// flow-typed version: <<STUB>>/promise-file-reader_v1.0.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-file-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-file-reader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-file-reader/PromiseFileReader_test' {
  declare module.exports: any;
}

declare module 'promise-file-reader/PromiseFileReader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-file-reader/PromiseFileReader_test.js' {
  declare module.exports: $Exports<
    'promise-file-reader/PromiseFileReader_test',
  >;
}
declare module 'promise-file-reader/PromiseFileReader.js' {
  declare module.exports: $Exports<'promise-file-reader/PromiseFileReader'>;
}
