// flow-typed signature: c4b4b1674187145543cac495eae45f4a
// flow-typed version: <<STUB>>/raf-throttle_v^2.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf-throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf-throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raf-throttle/lib/rafThrottle' {
  declare module.exports: any;
}

declare module 'raf-throttle/rafThrottle' {
  declare module.exports: any;
}

declare module 'raf-throttle/umd/rafThrottle' {
  declare module.exports: any;
}

declare module 'raf-throttle/umd/rafThrottle.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raf-throttle/lib/rafThrottle.js' {
  declare module.exports: $Exports<'raf-throttle/lib/rafThrottle'>;
}
declare module 'raf-throttle/rafThrottle.js' {
  declare module.exports: $Exports<'raf-throttle/rafThrottle'>;
}
declare module 'raf-throttle/umd/rafThrottle.js' {
  declare module.exports: $Exports<'raf-throttle/umd/rafThrottle'>;
}
declare module 'raf-throttle/umd/rafThrottle.min.js' {
  declare module.exports: $Exports<'raf-throttle/umd/rafThrottle.min'>;
}
