// flow-typed signature: 29fb76cc5efeb0346e7592b5b1a912f5
// flow-typed version: <<STUB>>/rc-scroll-anim_v2.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-scroll-anim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-scroll-anim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-scroll-anim/dist/rc-scroll-anim' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/dist/rc-scroll-anim.min' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/EventDispatcher' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/index' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/Mapped' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/ScrollElement' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/ScrollLink' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/ScrollOverPack' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/ScrollParallax' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/ScrollScreen' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/es/util' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/EventDispatcher' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/index' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/Mapped' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/ScrollElement' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/ScrollLink' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/ScrollOverPack' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/ScrollParallax' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/ScrollScreen' {
  declare module.exports: any;
}

declare module 'rc-scroll-anim/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-scroll-anim/dist/rc-scroll-anim.js' {
  declare module.exports: $Exports<'rc-scroll-anim/dist/rc-scroll-anim'>;
}
declare module 'rc-scroll-anim/dist/rc-scroll-anim.min.js' {
  declare module.exports: $Exports<'rc-scroll-anim/dist/rc-scroll-anim.min'>;
}
declare module 'rc-scroll-anim/es/EventDispatcher.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/EventDispatcher'>;
}
declare module 'rc-scroll-anim/es/index.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/index'>;
}
declare module 'rc-scroll-anim/es/Mapped.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/Mapped'>;
}
declare module 'rc-scroll-anim/es/ScrollElement.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/ScrollElement'>;
}
declare module 'rc-scroll-anim/es/ScrollLink.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/ScrollLink'>;
}
declare module 'rc-scroll-anim/es/ScrollOverPack.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/ScrollOverPack'>;
}
declare module 'rc-scroll-anim/es/ScrollParallax.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/ScrollParallax'>;
}
declare module 'rc-scroll-anim/es/ScrollScreen.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/ScrollScreen'>;
}
declare module 'rc-scroll-anim/es/util.js' {
  declare module.exports: $Exports<'rc-scroll-anim/es/util'>;
}
declare module 'rc-scroll-anim/lib/EventDispatcher.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/EventDispatcher'>;
}
declare module 'rc-scroll-anim/lib/index.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/index'>;
}
declare module 'rc-scroll-anim/lib/Mapped.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/Mapped'>;
}
declare module 'rc-scroll-anim/lib/ScrollElement.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/ScrollElement'>;
}
declare module 'rc-scroll-anim/lib/ScrollLink.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/ScrollLink'>;
}
declare module 'rc-scroll-anim/lib/ScrollOverPack.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/ScrollOverPack'>;
}
declare module 'rc-scroll-anim/lib/ScrollParallax.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/ScrollParallax'>;
}
declare module 'rc-scroll-anim/lib/ScrollScreen.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/ScrollScreen'>;
}
declare module 'rc-scroll-anim/lib/util.js' {
  declare module.exports: $Exports<'rc-scroll-anim/lib/util'>;
}
