// flow-typed signature: 2e8c8fafb8476f50e185b17535068613
// flow-typed version: <<STUB>>/rc-tween-one_v1.7.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-tween-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-tween-one' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-tween-one/dist/rc-tween-one' {
  declare module.exports: any;
}

declare module 'rc-tween-one/dist/rc-tween-one.min' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/easing' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/index' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugin/BezierPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugin/PathPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugin/snapsvglite' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugin/StylePlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugin/SvgDrawPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugin/SvgMorphPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/plugins' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/ticker' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/Tween' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/TweenOne' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/TweenOneGroup' {
  declare module.exports: any;
}

declare module 'rc-tween-one/es/util' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/easing' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/index' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugin/BezierPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugin/PathPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugin/snapsvglite' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugin/StylePlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugin/SvgDrawPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugin/SvgMorphPlugin' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/plugins' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/ticker' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/Tween' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/TweenOne' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/TweenOneGroup' {
  declare module.exports: any;
}

declare module 'rc-tween-one/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-tween-one/dist/rc-tween-one.js' {
  declare module.exports: $Exports<'rc-tween-one/dist/rc-tween-one'>;
}
declare module 'rc-tween-one/dist/rc-tween-one.min.js' {
  declare module.exports: $Exports<'rc-tween-one/dist/rc-tween-one.min'>;
}
declare module 'rc-tween-one/es/easing.js' {
  declare module.exports: $Exports<'rc-tween-one/es/easing'>;
}
declare module 'rc-tween-one/es/index.js' {
  declare module.exports: $Exports<'rc-tween-one/es/index'>;
}
declare module 'rc-tween-one/es/plugin/BezierPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugin/BezierPlugin'>;
}
declare module 'rc-tween-one/es/plugin/PathPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugin/PathPlugin'>;
}
declare module 'rc-tween-one/es/plugin/snapsvglite.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugin/snapsvglite'>;
}
declare module 'rc-tween-one/es/plugin/StylePlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugin/StylePlugin'>;
}
declare module 'rc-tween-one/es/plugin/SvgDrawPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugin/SvgDrawPlugin'>;
}
declare module 'rc-tween-one/es/plugin/SvgMorphPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugin/SvgMorphPlugin'>;
}
declare module 'rc-tween-one/es/plugins.js' {
  declare module.exports: $Exports<'rc-tween-one/es/plugins'>;
}
declare module 'rc-tween-one/es/ticker.js' {
  declare module.exports: $Exports<'rc-tween-one/es/ticker'>;
}
declare module 'rc-tween-one/es/Tween.js' {
  declare module.exports: $Exports<'rc-tween-one/es/Tween'>;
}
declare module 'rc-tween-one/es/TweenOne.js' {
  declare module.exports: $Exports<'rc-tween-one/es/TweenOne'>;
}
declare module 'rc-tween-one/es/TweenOneGroup.js' {
  declare module.exports: $Exports<'rc-tween-one/es/TweenOneGroup'>;
}
declare module 'rc-tween-one/es/util.js' {
  declare module.exports: $Exports<'rc-tween-one/es/util'>;
}
declare module 'rc-tween-one/lib/easing.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/easing'>;
}
declare module 'rc-tween-one/lib/index.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/index'>;
}
declare module 'rc-tween-one/lib/plugin/BezierPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugin/BezierPlugin'>;
}
declare module 'rc-tween-one/lib/plugin/PathPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugin/PathPlugin'>;
}
declare module 'rc-tween-one/lib/plugin/snapsvglite.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugin/snapsvglite'>;
}
declare module 'rc-tween-one/lib/plugin/StylePlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugin/StylePlugin'>;
}
declare module 'rc-tween-one/lib/plugin/SvgDrawPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugin/SvgDrawPlugin'>;
}
declare module 'rc-tween-one/lib/plugin/SvgMorphPlugin.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugin/SvgMorphPlugin'>;
}
declare module 'rc-tween-one/lib/plugins.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/plugins'>;
}
declare module 'rc-tween-one/lib/ticker.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/ticker'>;
}
declare module 'rc-tween-one/lib/Tween.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/Tween'>;
}
declare module 'rc-tween-one/lib/TweenOne.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/TweenOne'>;
}
declare module 'rc-tween-one/lib/TweenOneGroup.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/TweenOneGroup'>;
}
declare module 'rc-tween-one/lib/util.js' {
  declare module.exports: $Exports<'rc-tween-one/lib/util'>;
}
