// flow-typed signature: f30e4d797aab95e841097973b4ba8832
// flow-typed version: <<STUB>>/react-responsive_v4.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive/dist/react-responsive' {
  declare module.exports: any;
}

declare module 'react-responsive/dist/react-responsive.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive/dist/react-responsive.js' {
  declare module.exports: $Exports<'react-responsive/dist/react-responsive'>;
}
declare module 'react-responsive/dist/react-responsive.min.js' {
  declare module.exports: $Exports<
    'react-responsive/dist/react-responsive.min',
  >;
}
