// flow-typed signature: d0471d0dc3cb4c65d61037886f25f4d8
// flow-typed version: <<STUB>>/react-snap_v1.11.4/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-snap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-snap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-snap/run' {
  declare module.exports: any;
}

declare module 'react-snap/src/puppeteer_utils' {
  declare module.exports: any;
}

declare module 'react-snap/vendor/preload_polyfill.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-snap/index' {
  declare module.exports: $Exports<'react-snap'>;
}
declare module 'react-snap/index.js' {
  declare module.exports: $Exports<'react-snap'>;
}
declare module 'react-snap/run.js' {
  declare module.exports: $Exports<'react-snap/run'>;
}
declare module 'react-snap/src/puppeteer_utils.js' {
  declare module.exports: $Exports<'react-snap/src/puppeteer_utils'>;
}
declare module 'react-snap/vendor/preload_polyfill.min.js' {
  declare module.exports: $Exports<'react-snap/vendor/preload_polyfill.min'>;
}
