// flow-typed signature: 086ae8ef8e9ff4dd29fe5eb865098ffb
// flow-typed version: <<STUB>>/react-render-to-json_v^0.0.6/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-render-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-render-to-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-render-to-json/lib/renderToJson' {
  declare module.exports: any;
}

declare module 'react-render-to-json/src/renderToJson' {
  declare module.exports: any;
}

declare module 'react-render-to-json/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-render-to-json/lib/renderToJson.js' {
  declare module.exports: $Exports<'react-render-to-json/lib/renderToJson'>;
}
declare module 'react-render-to-json/src/renderToJson.js' {
  declare module.exports: $Exports<'react-render-to-json/src/renderToJson'>;
}
declare module 'react-render-to-json/test.js' {
  declare module.exports: $Exports<'react-render-to-json/test'>;
}
