// flow-typed signature: 93a7883767b7046d9f108c5b7d8f33be
// flow-typed version: <<STUB>>/react-motion-ui-pack_v^0.10.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-motion-ui-pack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-motion-ui-pack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-motion-ui-pack/dist/react-motion-ui-pack' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/dist/react-motion-ui-pack.min' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/config-to-style' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/from-RM-styles' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/is-element' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/react-motion-ui-pack' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/special-assign' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/to-RM-styles' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/Transition' {
  declare module.exports: any;
}

declare module 'react-motion-ui-pack/lib/ui-pack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-motion-ui-pack/dist/react-motion-ui-pack.js' {
  declare module.exports: $Exports<
    'react-motion-ui-pack/dist/react-motion-ui-pack',
  >;
}
declare module 'react-motion-ui-pack/dist/react-motion-ui-pack.min.js' {
  declare module.exports: $Exports<
    'react-motion-ui-pack/dist/react-motion-ui-pack.min',
  >;
}
declare module 'react-motion-ui-pack/lib/config-to-style.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/config-to-style'>;
}
declare module 'react-motion-ui-pack/lib/from-RM-styles.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/from-RM-styles'>;
}
declare module 'react-motion-ui-pack/lib/is-element.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/is-element'>;
}
declare module 'react-motion-ui-pack/lib/react-motion-ui-pack.js' {
  declare module.exports: $Exports<
    'react-motion-ui-pack/lib/react-motion-ui-pack',
  >;
}
declare module 'react-motion-ui-pack/lib/special-assign.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/special-assign'>;
}
declare module 'react-motion-ui-pack/lib/to-RM-styles.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/to-RM-styles'>;
}
declare module 'react-motion-ui-pack/lib/Transition.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/Transition'>;
}
declare module 'react-motion-ui-pack/lib/ui-pack.js' {
  declare module.exports: $Exports<'react-motion-ui-pack/lib/ui-pack'>;
}
