// flow-typed signature: 1513ff87035cea5aed4792c02fcfac45
// flow-typed version: <<STUB>>/react-topbar-progress-indicator_v2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-topbar-progress-indicator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-topbar-progress-indicator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-topbar-progress-indicator/lib/index' {
  declare module.exports: any;
}

declare module 'react-topbar-progress-indicator/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-topbar-progress-indicator/lib/index.js' {
  declare module.exports: $Exports<'react-topbar-progress-indicator/lib/index'>;
}
declare module 'react-topbar-progress-indicator/src/index.js' {
  declare module.exports: $Exports<'react-topbar-progress-indicator/src/index'>;
}
