// flow-typed signature: de7f0f686ddaf48937951c275b955ee2
// flow-typed version: <<STUB>>/react-dnd-dropzone_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-dropzone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-dropzone/lib/Dropzone' {
  declare module.exports: any;
}

declare module 'react-dnd-dropzone/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-dropzone/lib/Dropzone.js' {
  declare module.exports: $Exports<'react-dnd-dropzone/lib/Dropzone'>;
}
declare module 'react-dnd-dropzone/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-dropzone/lib/index'>;
}
