// flow-typed signature: 0e257ef2149eb5d57d77bae1422f9a00
// flow-typed version: <<STUB>>/react-intl-po_v2.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-po'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-po' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-po/lib/cli' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/extractAndWritePOTFromMessagesSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/filterPOAndWriteTranslateSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/index' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/potFormater' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/potHeader' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/readAllMessageAsObjectSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/readAllPOAsObjectSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/lib/utils/po2jsonHelper' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/cli' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/extractAndWritePOTFromMessagesSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/filterPOAndWriteTranslateSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/index' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/potFormater' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/potHeader' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/readAllMessageAsObjectSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/readAllPOAsObjectSync' {
  declare module.exports: any;
}

declare module 'react-intl-po/src/utils/po2jsonHelper' {
  declare module.exports: any;
}

declare module 'react-intl-po/test/extractAndWritePOTFromMessagesSync.test' {
  declare module.exports: any;
}

declare module 'react-intl-po/test/filterPOAndWriteTranslateSync.test' {
  declare module.exports: any;
}

declare module 'react-intl-po/test/potFormater.test' {
  declare module.exports: any;
}

declare module 'react-intl-po/test/potHeader.test' {
  declare module.exports: any;
}

declare module 'react-intl-po/test/readAllMessageAsObjectSync.test' {
  declare module.exports: any;
}

declare module 'react-intl-po/test/readAllPOAsObjectSync.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-po/lib/cli.js' {
  declare module.exports: $Exports<'react-intl-po/lib/cli'>;
}
declare module 'react-intl-po/lib/extractAndWritePOTFromMessagesSync.js' {
  declare module.exports: $Exports<
    'react-intl-po/lib/extractAndWritePOTFromMessagesSync',
  >;
}
declare module 'react-intl-po/lib/filterPOAndWriteTranslateSync.js' {
  declare module.exports: $Exports<
    'react-intl-po/lib/filterPOAndWriteTranslateSync',
  >;
}
declare module 'react-intl-po/lib/index.js' {
  declare module.exports: $Exports<'react-intl-po/lib/index'>;
}
declare module 'react-intl-po/lib/potFormater.js' {
  declare module.exports: $Exports<'react-intl-po/lib/potFormater'>;
}
declare module 'react-intl-po/lib/potHeader.js' {
  declare module.exports: $Exports<'react-intl-po/lib/potHeader'>;
}
declare module 'react-intl-po/lib/readAllMessageAsObjectSync.js' {
  declare module.exports: $Exports<
    'react-intl-po/lib/readAllMessageAsObjectSync',
  >;
}
declare module 'react-intl-po/lib/readAllPOAsObjectSync.js' {
  declare module.exports: $Exports<'react-intl-po/lib/readAllPOAsObjectSync'>;
}
declare module 'react-intl-po/lib/utils/po2jsonHelper.js' {
  declare module.exports: $Exports<'react-intl-po/lib/utils/po2jsonHelper'>;
}
declare module 'react-intl-po/src/cli.js' {
  declare module.exports: $Exports<'react-intl-po/src/cli'>;
}
declare module 'react-intl-po/src/extractAndWritePOTFromMessagesSync.js' {
  declare module.exports: $Exports<
    'react-intl-po/src/extractAndWritePOTFromMessagesSync',
  >;
}
declare module 'react-intl-po/src/filterPOAndWriteTranslateSync.js' {
  declare module.exports: $Exports<
    'react-intl-po/src/filterPOAndWriteTranslateSync',
  >;
}
declare module 'react-intl-po/src/index.js' {
  declare module.exports: $Exports<'react-intl-po/src/index'>;
}
declare module 'react-intl-po/src/potFormater.js' {
  declare module.exports: $Exports<'react-intl-po/src/potFormater'>;
}
declare module 'react-intl-po/src/potHeader.js' {
  declare module.exports: $Exports<'react-intl-po/src/potHeader'>;
}
declare module 'react-intl-po/src/readAllMessageAsObjectSync.js' {
  declare module.exports: $Exports<
    'react-intl-po/src/readAllMessageAsObjectSync',
  >;
}
declare module 'react-intl-po/src/readAllPOAsObjectSync.js' {
  declare module.exports: $Exports<'react-intl-po/src/readAllPOAsObjectSync'>;
}
declare module 'react-intl-po/src/utils/po2jsonHelper.js' {
  declare module.exports: $Exports<'react-intl-po/src/utils/po2jsonHelper'>;
}
declare module 'react-intl-po/test/extractAndWritePOTFromMessagesSync.test.js' {
  declare module.exports: $Exports<
    'react-intl-po/test/extractAndWritePOTFromMessagesSync.test',
  >;
}
declare module 'react-intl-po/test/filterPOAndWriteTranslateSync.test.js' {
  declare module.exports: $Exports<
    'react-intl-po/test/filterPOAndWriteTranslateSync.test',
  >;
}
declare module 'react-intl-po/test/potFormater.test.js' {
  declare module.exports: $Exports<'react-intl-po/test/potFormater.test'>;
}
declare module 'react-intl-po/test/potHeader.test.js' {
  declare module.exports: $Exports<'react-intl-po/test/potHeader.test'>;
}
declare module 'react-intl-po/test/readAllMessageAsObjectSync.test.js' {
  declare module.exports: $Exports<
    'react-intl-po/test/readAllMessageAsObjectSync.test',
  >;
}
declare module 'react-intl-po/test/readAllPOAsObjectSync.test.js' {
  declare module.exports: $Exports<
    'react-intl-po/test/readAllPOAsObjectSync.test',
  >;
}
