// flow-typed signature: 2ab50a3eed3460cf3de6ab9d5a9b8f33
// flow-typed version: <<STUB>>/react-overlay-pack_v^1.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-overlay-pack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-overlay-pack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-overlay-pack/lib/ClickOutside/ClickOutside' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/ClickOutside/ClickOutside.test' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/ClickOutside/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/Dialog/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/DomAlign/DomAlign' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/DomAlign/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/Overlay/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/Overlay/Overlay' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/Portal/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/Transition/index' {
  declare module.exports: any;
}

declare module 'react-overlay-pack/lib/utils/emptyFunction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-overlay-pack/lib/ClickOutside/ClickOutside.js' {
  declare module.exports: $Exports<
    'react-overlay-pack/lib/ClickOutside/ClickOutside',
  >;
}
declare module 'react-overlay-pack/lib/ClickOutside/ClickOutside.test.js' {
  declare module.exports: $Exports<
    'react-overlay-pack/lib/ClickOutside/ClickOutside.test',
  >;
}
declare module 'react-overlay-pack/lib/ClickOutside/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/ClickOutside/index'>;
}
declare module 'react-overlay-pack/lib/Dialog/Dialog.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/Dialog/Dialog'>;
}
declare module 'react-overlay-pack/lib/Dialog/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/Dialog/index'>;
}
declare module 'react-overlay-pack/lib/DomAlign/DomAlign.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/DomAlign/DomAlign'>;
}
declare module 'react-overlay-pack/lib/DomAlign/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/DomAlign/index'>;
}
declare module 'react-overlay-pack/lib/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/index'>;
}
declare module 'react-overlay-pack/lib/Overlay/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/Overlay/index'>;
}
declare module 'react-overlay-pack/lib/Overlay/Overlay.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/Overlay/Overlay'>;
}
declare module 'react-overlay-pack/lib/Portal/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/Portal/index'>;
}
declare module 'react-overlay-pack/lib/Transition/index.js' {
  declare module.exports: $Exports<'react-overlay-pack/lib/Transition/index'>;
}
declare module 'react-overlay-pack/lib/utils/emptyFunction.js' {
  declare module.exports: $Exports<
    'react-overlay-pack/lib/utils/emptyFunction',
  >;
}
