// flow-typed signature: 90e7f05ca9a03ba3707d2effc6bd3914
// flow-typed version: <<STUB>>/redux-cycles_v0.4.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-cycles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-cycles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-cycles/dist/combineCycles' {
  declare module.exports: any;
}

declare module 'redux-cycles/dist/createCycleMiddleware' {
  declare module.exports: any;
}

declare module 'redux-cycles/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-cycles/dist/combineCycles.js' {
  declare module.exports: $Exports<'redux-cycles/dist/combineCycles'>;
}
declare module 'redux-cycles/dist/createCycleMiddleware.js' {
  declare module.exports: $Exports<'redux-cycles/dist/createCycleMiddleware'>;
}
declare module 'redux-cycles/dist/index.js' {
  declare module.exports: $Exports<'redux-cycles/dist/index'>;
}
