// flow-typed signature: fe86b7ddaad10e8ca6fba912aed87a8c
// flow-typed version: <<STUB>>/svgr.macro_v^1.0.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgr.macro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svgr.macro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svgr.macro/lib/index' {
  declare module.exports: any;
}

declare module 'svgr.macro/lib/macro' {
  declare module.exports: any;
}

declare module 'svgr.macro/lib/utils/getArguments' {
  declare module.exports: any;
}

declare module 'svgr.macro/lib/utils/importReact' {
  declare module.exports: any;
}

declare module 'svgr.macro/lib/utils/optionToCLI' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svgr.macro/lib/index.js' {
  declare module.exports: $Exports<'svgr.macro/lib/index'>;
}
declare module 'svgr.macro/lib/macro.js' {
  declare module.exports: $Exports<'svgr.macro/lib/macro'>;
}
declare module 'svgr.macro/lib/utils/getArguments.js' {
  declare module.exports: $Exports<'svgr.macro/lib/utils/getArguments'>;
}
declare module 'svgr.macro/lib/utils/importReact.js' {
  declare module.exports: $Exports<'svgr.macro/lib/utils/importReact'>;
}
declare module 'svgr.macro/lib/utils/optionToCLI.js' {
  declare module.exports: $Exports<'svgr.macro/lib/utils/optionToCLI'>;
}
