version: 2

# Reference variables.
references:
  docker_default: &docker_default
    working_directory: /tmp/app
    docker:
      - image: node:9.8.0
  move_to_workspace: &move_to_workspace
    run:
        name: Move to workspace
        command: |
          rm -rf .yarn-cache CHANGELOG.md README.md yarn.lock
          mkdir /tmp/workspace
          mv /tmp/app /tmp/workspace
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
        root: /tmp/workspace
        paths:
          - app/*
  attach_workspace: &attach_workspace
    attach_workspace:
      at: /tmp/workspace
  restore_from_workspace: &restore_from_workspace
    run:
      name: Restore app from workspace
      command: mv /tmp/workspace/app /tmp

jobs:
  # Check all the environment versions.
  versions:
    <<: *docker_default
    steps:
      - run: node --version
      - run: npm --version
      - run: yarn --version

  # Install NPM & Leran bootstrap & Cache.
  bootstrap:
    <<: *docker_default
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn install --pure-lockfile
      - run: yarn cache dir
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn-cache
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - *move_to_workspace
      - *persist_to_workspace

  # Linting eslint/flow/stylelint.
  lint:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_from_workspace
      - run: ./tasks/lint.sh
  # For unit testing of all packages.
  test:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_from_workspace
      - run: ./tasks/test.sh
  # For building demo page.
  test-page:
    <<: *docker_default
    steps:
      - *attach_workspace
      - *restore_from_workspace
      - run: ./tasks/test-page.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - versions
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - test:
          requires:
            - bootstrap
      - test-page:
          requires:
            - bootstrap
