// flow-typed signature: 33ec9350fa3b877fd2f91da7d80143e4
// flow-typed version: <<STUB>>/eslint-config-mcs-lite_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mcs-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mcs-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-mcs-lite/index' {
  declare module.exports: $Exports<'eslint-config-mcs-lite'>;
}
declare module 'eslint-config-mcs-lite/index.js' {
  declare module.exports: $Exports<'eslint-config-mcs-lite'>;
}
