// flow-typed signature: e0bb5a11d2bc10c7a4b09bb152d71d3e
// flow-typed version: <<STUB>>/@cycle/http_v14.8.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cycle/http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cycle/http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cycle/http/dist/cycle-http-driver' {
  declare module.exports: any;
}

declare module '@cycle/http/dist/cycle-http-driver.min' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/cjs/http-driver' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/cjs/index' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/cjs/interfaces' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/cjs/isolate' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/cjs/MainHTTPSource' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/es6/http-driver' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/es6/index' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/es6/interfaces' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/es6/isolate' {
  declare module.exports: any;
}

declare module '@cycle/http/lib/es6/MainHTTPSource' {
  declare module.exports: any;
}

declare module '@cycle/http/test/browser/lib/common' {
  declare module.exports: any;
}

declare module '@cycle/http/test/browser/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cycle/http/dist/cycle-http-driver.js' {
  declare module.exports: $Exports<'@cycle/http/dist/cycle-http-driver'>;
}
declare module '@cycle/http/dist/cycle-http-driver.min.js' {
  declare module.exports: $Exports<'@cycle/http/dist/cycle-http-driver.min'>;
}
declare module '@cycle/http/lib/cjs/http-driver.js' {
  declare module.exports: $Exports<'@cycle/http/lib/cjs/http-driver'>;
}
declare module '@cycle/http/lib/cjs/index.js' {
  declare module.exports: $Exports<'@cycle/http/lib/cjs/index'>;
}
declare module '@cycle/http/lib/cjs/interfaces.js' {
  declare module.exports: $Exports<'@cycle/http/lib/cjs/interfaces'>;
}
declare module '@cycle/http/lib/cjs/isolate.js' {
  declare module.exports: $Exports<'@cycle/http/lib/cjs/isolate'>;
}
declare module '@cycle/http/lib/cjs/MainHTTPSource.js' {
  declare module.exports: $Exports<'@cycle/http/lib/cjs/MainHTTPSource'>;
}
declare module '@cycle/http/lib/es6/http-driver.js' {
  declare module.exports: $Exports<'@cycle/http/lib/es6/http-driver'>;
}
declare module '@cycle/http/lib/es6/index.js' {
  declare module.exports: $Exports<'@cycle/http/lib/es6/index'>;
}
declare module '@cycle/http/lib/es6/interfaces.js' {
  declare module.exports: $Exports<'@cycle/http/lib/es6/interfaces'>;
}
declare module '@cycle/http/lib/es6/isolate.js' {
  declare module.exports: $Exports<'@cycle/http/lib/es6/isolate'>;
}
declare module '@cycle/http/lib/es6/MainHTTPSource.js' {
  declare module.exports: $Exports<'@cycle/http/lib/es6/MainHTTPSource'>;
}
declare module '@cycle/http/test/browser/lib/common.js' {
  declare module.exports: $Exports<'@cycle/http/test/browser/lib/common'>;
}
declare module '@cycle/http/test/browser/lib/index.js' {
  declare module.exports: $Exports<'@cycle/http/test/browser/lib/index'>;
}
