// flow-typed signature: ddbe15ed255f3c14dc792df54d5bb3ca
// flow-typed version: <<STUB>>/@cycle/rxjs-run_v8.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cycle/rxjs-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cycle/rxjs-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cycle/rxjs-run/dist/cycle' {
  declare module.exports: any;
}

declare module '@cycle/rxjs-run/dist/cycle.min' {
  declare module.exports: any;
}

declare module '@cycle/rxjs-run/lib/cjs/index' {
  declare module.exports: any;
}

declare module '@cycle/rxjs-run/lib/es6/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cycle/rxjs-run/dist/cycle.js' {
  declare module.exports: $Exports<'@cycle/rxjs-run/dist/cycle'>;
}
declare module '@cycle/rxjs-run/dist/cycle.min.js' {
  declare module.exports: $Exports<'@cycle/rxjs-run/dist/cycle.min'>;
}
declare module '@cycle/rxjs-run/lib/cjs/index.js' {
  declare module.exports: $Exports<'@cycle/rxjs-run/lib/cjs/index'>;
}
declare module '@cycle/rxjs-run/lib/es6/index.js' {
  declare module.exports: $Exports<'@cycle/rxjs-run/lib/es6/index'>;
}
