// flow-typed signature: be23b9d0ed3bcfc36903d385902315f0
// flow-typed version: <<STUB>>/@cycle/storage_v5.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cycle/storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cycle/storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cycle/storage/example/app' {
  declare module.exports: any;
}

declare module '@cycle/storage/lib/index' {
  declare module.exports: any;
}

declare module '@cycle/storage/lib/responseCollection' {
  declare module.exports: any;
}

declare module '@cycle/storage/lib/util' {
  declare module.exports: any;
}

declare module '@cycle/storage/lib/writeToStore' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cycle/storage/example/app.js' {
  declare module.exports: $Exports<'@cycle/storage/example/app'>;
}
declare module '@cycle/storage/lib/index.js' {
  declare module.exports: $Exports<'@cycle/storage/lib/index'>;
}
declare module '@cycle/storage/lib/responseCollection.js' {
  declare module.exports: $Exports<'@cycle/storage/lib/responseCollection'>;
}
declare module '@cycle/storage/lib/util.js' {
  declare module.exports: $Exports<'@cycle/storage/lib/util'>;
}
declare module '@cycle/storage/lib/writeToStore.js' {
  declare module.exports: $Exports<'@cycle/storage/lib/writeToStore'>;
}
