// flow-typed signature: 0bfdca240312e7d06e552c136fc34145
// flow-typed version: <<STUB>>/@cycle/time_v0.8.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cycle/time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cycle/time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cycle/time/dist/animation-frames' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/assert-equal' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/debounce' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/delay' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/diagram' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/index' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/log-to-svg-diagram' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/mock-time-source' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/periodic' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/record' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/run-virtually' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/scheduler' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/throttle-animation' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/throttle' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/time-driver' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/time-source' {
  declare module.exports: any;
}

declare module '@cycle/time/dist/tween' {
  declare module.exports: any;
}

declare module '@cycle/time/most' {
  declare module.exports: any;
}

declare module '@cycle/time/rxjs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cycle/time/dist/animation-frames.js' {
  declare module.exports: $Exports<'@cycle/time/dist/animation-frames'>;
}
declare module '@cycle/time/dist/assert-equal.js' {
  declare module.exports: $Exports<'@cycle/time/dist/assert-equal'>;
}
declare module '@cycle/time/dist/debounce.js' {
  declare module.exports: $Exports<'@cycle/time/dist/debounce'>;
}
declare module '@cycle/time/dist/delay.js' {
  declare module.exports: $Exports<'@cycle/time/dist/delay'>;
}
declare module '@cycle/time/dist/diagram.js' {
  declare module.exports: $Exports<'@cycle/time/dist/diagram'>;
}
declare module '@cycle/time/dist/index.js' {
  declare module.exports: $Exports<'@cycle/time/dist/index'>;
}
declare module '@cycle/time/dist/log-to-svg-diagram.js' {
  declare module.exports: $Exports<'@cycle/time/dist/log-to-svg-diagram'>;
}
declare module '@cycle/time/dist/mock-time-source.js' {
  declare module.exports: $Exports<'@cycle/time/dist/mock-time-source'>;
}
declare module '@cycle/time/dist/periodic.js' {
  declare module.exports: $Exports<'@cycle/time/dist/periodic'>;
}
declare module '@cycle/time/dist/record.js' {
  declare module.exports: $Exports<'@cycle/time/dist/record'>;
}
declare module '@cycle/time/dist/run-virtually.js' {
  declare module.exports: $Exports<'@cycle/time/dist/run-virtually'>;
}
declare module '@cycle/time/dist/scheduler.js' {
  declare module.exports: $Exports<'@cycle/time/dist/scheduler'>;
}
declare module '@cycle/time/dist/throttle-animation.js' {
  declare module.exports: $Exports<'@cycle/time/dist/throttle-animation'>;
}
declare module '@cycle/time/dist/throttle.js' {
  declare module.exports: $Exports<'@cycle/time/dist/throttle'>;
}
declare module '@cycle/time/dist/time-driver.js' {
  declare module.exports: $Exports<'@cycle/time/dist/time-driver'>;
}
declare module '@cycle/time/dist/time-source.js' {
  declare module.exports: $Exports<'@cycle/time/dist/time-source'>;
}
declare module '@cycle/time/dist/tween.js' {
  declare module.exports: $Exports<'@cycle/time/dist/tween'>;
}
declare module '@cycle/time/most.js' {
  declare module.exports: $Exports<'@cycle/time/most'>;
}
declare module '@cycle/time/rxjs.js' {
  declare module.exports: $Exports<'@cycle/time/rxjs'>;
}
